# Netlify configuration
[build]
  publish = "dist"
  command = "npm run build"

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/portfolio.html"
  status = 200

[[redirects]]
  from = "/guarantees"
  to = "/guarantees.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/cookie-policy"
  to = "/cookie-policy.html"
  status = 200

[[redirects]]
  from = "/disclaimer"
  to = "/disclaimer.html"
  status = 200

# Handle assets and API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback for any other routes to index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200